lava-nc/lava

lava/magma/core/decorator.py, tests/magma/core/model/test_decorators.py
Signed-off-by: Risbud, Sumedh <sumedh.risbud@intel.com>
=> Added @tags decorator to tag ProcessModels and distinguish them

lava/magma/compiler/builder.py, lava/magma/core/model/interfaces.py, lava/magma/core/model/py/ports.py, tests/magma/core/model/test_py_model.py
simple implementation for review to promote design discussion
=> Issue11: forking/joining ports strawman 

src/lava/magma/core/LICENSE, src/lava/proc/LICENSE, src/lava/tutorials/LICENSE
Signed-off-by: Mathis Richter <mathis.richter@intel.com>
=> Fixed copyright in BSD-3 LICENSE files

README.md, src/lava/tutorials/in_depth/tutorial01_installing_lava.ipynb
=> Fixed PYTHONPATH installation instructions after directory restructure of core lava repo

src/lava/proc/monitor/models.py, tests/lava/proc/monitor/test_monitors.py
Signed-off-by: Mathis Richter <mathis.richter@intel.com>
=> Fix for issue #109, Monitor unit test failing non-deterministically

README.md, build.py
=> Lava 0.2.0

src/lava/proc/io/reset.py
Signed-off-by: bamsumit <bam_sumit@hotmail.com>
Issue Number: 
- io.reset timing is off by 1 step compared to dataset and read processes
- io.reset behaves same as dataset and read processes
=> Fixed reset timing offset

poetry.lock, pyproject.toml, tests/lava/magma/runtime/test_ref_var_ports.py
Issue Number: 
- test_ref_var_ports fails non-deterministically
- test_ref_var_ports should always pass
=> Added wait() to refvar unittests

README.md
=> Update README.md remove vlab instructions

.github/workflows/ci-build.yml, poetry.lock, pyproject.toml
=> add cpplint dependence

README.md
Issue Number: 
Objective of pull request: Add intel numpy to conda install instructions
=> Add intel numpy to conda install instructions

.github/workflows/ci-build.yml, src/lava/magma/runtime/message_infrastructure/include/abstract_actor.h, src/lava/magma/runtime/message_infrastructure/include/abstract_channel.h, src/lava/magma/runtime/message_infrastructure/include/abstract_port.h, src/lava/magma/runtime/message_infrastructure/include/abstract_port_implementation.h, src/lava/magma/runtime/message_infrastructure/include/multiprocessing.h, src/lava/magma/runtime/message_infrastructure/include/process_model.h, src/lava/magma/runtime/message_infrastructure/include/runtime.h, src/lava/magma/runtime/message_infrastructure/include/shm.h, src/lava/magma/runtime/message_infrastructure/include/shmem_channel.h, src/lava/magma/runtime/message_infrastructure/include/shmem_port.h, src/lava/magma/runtime/message_infrastructure/include/utils.h
=> Fix cpplint warnings & errors

src/lava/magma/compiler/compiler.py, src/lava/magma/core/run_configs.py
=> Make Pre Post Functions execution on board

.github/workflows/ci-build.yml, poetry.lock, src/lava/magma/runtime/message_infrastructure/CMakeLists.txt, src/lava/magma/runtime/message_infrastructure/message_infrastructure/__init__.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/abstract_actor.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/message_infrastructure_py_wrapper.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/multiprocessing.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/multiprocessing.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/posix_actor.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/py_middle_layer.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/py_middle_layer.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/py_middle_layer_test.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/transformer.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/transformer.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/utils.h, src/lava/magma/runtime/message_infrastructure/poetry.lock, src/lava/magma/runtime/message_infrastructure/pyproject.toml, src/lava/magma/runtime/message_infrastructure/setup.py, src/lava/magma/runtime/message_infrastructure/test/test_multiprocessing.py, src/lava/magma/runtime/message_infrastructure/test/test_simple_port.py, src/lava/magma/runtime/message_infrastructure/test/test_transformer.py, src/lava/magma/runtime/message_infrastructure/test/test_xport.py
Add Actor feature
Signed-off-by: Miao, Hongda <hongda.miao@intel.com>
Issue Number: 
-
-
=> MultiProcessing&Actor Implementation

src/lava/magma/runtime/message_infrastructure/CMakeLists.txt, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/message_infrastructure_py_wrapper.cc, src/lava/magma/runtime/message_infrastructure/poetry.lock, src/lava/magma/runtime/message_infrastructure/pyproject.toml, src/lava/magma/runtime/message_infrastructure/test/test_multiprocessing.py
- add psutil into dev dependencies
Issue Number: 
-
-
=> Restore ports api

src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/abstract_actor.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/posix_actor.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shmem_port.cc
Signed-off-by: Xu, He <he.xu@intel.com>
Issue Number: 
-
-
=> Fix actor build error

src/lava/magma/runtime/message_infrastructure/CMakeLists.txt, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/abstract_actor.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/abstract_actor.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/abstract_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/abstract_port.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/abstract_port_implementation.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel_proxy.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/message_infrastructure_logging.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/message_infrastructure_py_wrapper.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/multiprocessing.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/multiprocessing.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/port_proxy.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/ports.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/posix_actor.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shmem_channel.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shmem_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shmem_port.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py, src/lava/magma/runtime/message_infrastructure/test/test_multiprocessing.py
=> refactor the structure of abstract_port

src/lava/magma/compiler/builders/channel_builder.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure/__init__.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shmem_port.cc
=> fix fail at test_channel_builder.py

pyproject.toml
Objective of pull request: Transfer dev deps to dev section, they are not needed to run Lava, but only for development or working with jupyter notebooks or testing.
=> Transfer dev deps to dev section: Update pyproject.toml

src/lava/proc/cost_integrator/models.py, src/lava/proc/cost_integrator/process.py, src/lava/proc/read_gate/models.py, src/lava/proc/read_gate/process.py, src/lava/proc/receiver/models.py, src/lava/proc/receiver/process.py, src/lava/proc/spiker/models.py, src/lava/proc/spiker/process.py, tests/lava/proc/spiker/test_models.py
Objective of pull request: 
Provide all public processes for GG's optimization solver.
Note: All process.py and models.py are from GG's private repo. I only added a new models.py for Spiker, as well as the corresponding unit test.
=> Public processes for optimization solver

.github/workflows/ci-build.yml
=> Update poetry version in CI

src/lava/magma/compiler/compiler_graphs.py, src/lava/magma/core/model/sub/model.py
Signed-off-by: GaboFGuerra <gabriel.fonseca.guerra@intel.com>
Issue Number: 
-
-
=> Enable exception proc_map, working with dataclasses, etc.

README.md, src/lava/proc/io/encoder.py, tutorials/in_depth/tutorial08_stdp.ipynb, tutorials/in_depth/tutorial09_custom_learning_rules.ipynb
=> Doc/fix for 0.5 release

.github/workflows/ci-build.yml, src/lava/magma/compiler/utils.py, src/lava/magma/core/model/py/model.py, src/lava/magma/core/model/py/ports.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure/__init__.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/message_infrastructure_py_wrapper.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shm.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/shmem_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure/ports.py, src/lava/magma/runtime/runtime.py, src/lava/magma/runtime/runtime_services/runtime_service.py, tests/lava/magma/compiler/channels/test_channel.py, tests/lava/magma/core/model/py/test_ports.py, tests/lava/magma/runtime/test_exception_handling.py, tests/lava/magma/runtime/test_get_set_non_determinism.py, tests/lava/magma/runtime/test_runtime_service.py, tests/lava/proc/dense/test_models.py, tests/lava/proc/io/test_dataloader.py, tests/lava/proc/io/test_source_sink.py, tests/lava/proc/monitor/test_monitors.py, tests/lava/proc/sdn/test_models.py, tests/lava/tutorials/test_tutorials.py
=> Pausing pipeline

.github/workflows/ci-build.yml
=> Msg infr ci task enabling

tests/lava/proc/sdn/test_models.py
=> Fix segment fault at sdn/test_models.py

src/lava/magma/runtime/message_infrastructure/CMakeLists.txt, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_channel.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_channel.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_port.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/abstract_channel.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/channel_factory.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/message_infrastructure_logging.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/utils.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/message_infrastructure_py_wrapper.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/port_proxy.cc, src/lava/magma/runtime/message_infrastructure/test/test_channel.py
Signed-off-by: Xu, He <he.xu@intel.com>
Issue Number: 
-
-
=> Add SocketChannel Implementaion

src/lava/magma/core/run_configs.py
=> Fixed bug in pre and post execution function hook

tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb
Issue Number: #434 
Objective of pull request: update the MNIST tutorial to add instructions to download the pretrained weights from GitHub LFS
=> Update MNIST tutorial

src/lava/utils/profiler.py
Objective of pull request: Renamed module which imports Loihi2HWProfiler, add correct type hints and fix typo.
- Name of the module of the Loihi2HWProfiler is wrong.
- Name of module is correct.
=> Bugfix Profiler base class

poetry.lock, pyproject.toml
* updated pytest to >7.2.0 -> remove depedency on unmaintained py project
* updated nbconvert to >7.2.0 -> update dependency mistune to latest version
Issue Number: 446
Objective of pull request: update two dependencies.
-
-
=> Dependabot and Snyk Updates

.github/workflows/cd.yml, .github/workflows/ci.yml, pyproject.toml
Objective of pull request: Test and Fix cd.yml
=> Test and Fix cd.yml

poetry.lock, pyproject.toml
Issue Number: 
Objective of pull request: Updated version number to 0.5.1 for release.
-
-
=> Updated version number to 0.5.1.

.github/workflows/ci-build.yml, src/lava/magma/runtime/message_infrastructure/test/test_channel.py
=> Fix grpc ci

src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shm.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shm.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shmem_channel.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shmem_channel.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shmem_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shmem_port.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/common.h, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_shm_delivery.cc
- When size equals 1, use ShmemBlockRecvPort.
- Fix offset at mdata.
Issue Number: 
-
-
=> Support blocking shmem recv port

src/lava/magma/runtime/message_infrastructure/CMakeLists.txt, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/utils.h
Default is OFF.
Issue Number: 
-
-
=> Add ENABLE_MM_PAUSE option

src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/dds/fast_dds.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_channel.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shm.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shmem_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_channel.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/abstract_channel.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/channel_factory.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/common.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/message_infrastructure_logging.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/message_infrastructure_logging.h, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/port_proxy.cc, src/lava/magma/runtime/message_infrastructure/test/test_shm_delivery.py
Signed-off-by: Wenhui Ye <wenhui.ye@intel.com>
Issue Number: 
-
-
=> change all NULL to nullptr

src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_port.cc, src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/utils.h, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_ddschannel.cc, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_grpc_delivery.cc, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_shm_delivery.cc, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_socket_delivery.cc
=> Wye feature convert carray to metadata

tests/lava/tutorials/test_tutorials.py
=> try to fix test tutorial

tests/lava/tutorials/test_tutorials.py, tutorials/in_depth/tutorial03_process_models.ipynb, tutorials/in_depth/tutorial04_execution.ipynb
=> fix fails at test_tutorials

src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/utils.h, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_ddschannel.cc, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_grpc_delivery.cc, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_shm_delivery.cc, src/lava/magma/runtime/message_infrastructure/test/cpptest/test_socket_delivery.cc
=> Fix grpcut bug

src/lava/magma/core/model/py/model.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure/__init__.py, src/lava/magma/runtime/runtime_services/runtime_service.py
=> Restore stop cmd between service and model

src/lava/magma/runtime/message_infrastructure/README.md, src/lava/magma/runtime/message_infrastructure/pyproject.toml, src/lava/magma/runtime/message_infrastructure/setup.py
=> update version to v0.2.1

.github/workflows/cd.yml, prebuild.py, pyproject.toml
=> Fix cd fail at msglib

tests/lava/proc/dense/test_stdp_sim.py
=> Fix pyut for msglib

pyproject.toml
=> release v6.0.0

src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/README.md
Signed-off-by: Miao, Hongda <hongda.miao@intel.com>
Issue Number: 
-
-
=> Update README file for communication between ROS and DDS

src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_fastdds_from_ros_realsense.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_ros_data_getter.py
Signed-off-by: szc321 <zongcai.shi@intel.com>
Issue Number: 
-
-
=> add channel_info

src/lava/magma/compiler/builders/channel_builder.py, src/lava/magma/compiler/utils.py, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel_proxy.cc, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel_proxy.h, src/lava/magma/runtime/_c_message_infrastructure/csrc/message_infrastructure_py_wrapper.cc, src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.cc, src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.h, src/lava/magma/runtime/message_infrastructure/ports.py, tests/lava/magma/runtime/message_infrastructure/test_channel.py, tests/lava/magma/runtime/message_infrastructure/test_temp_channel.py
Signed-off-by: Miao, Hongda <hongda.miao@intel.com>
Issue Number: 
-
-
=> Enable shape and type for ProxyPort

src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_fastdds_from_ros_dvs.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_fastdds_from_ros_realsense.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_ros_data_getter.py
=> getter amend

src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/demo/app.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/demo/dvs_file_input/process.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/demo/process_out/process.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/demo/rate_reader/process.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/demo/ros_realsense_input/process.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/demo/sparse/process.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_fastdds_from_ros_realsense.py
=> demo ROS camera connecting with dnf

.github/workflows/ci.yml, src/lava/magma/runtime/_c_message_infrastructure/test/CMakeLists.txt, src/lava/magma/runtime/_c_message_infrastructure/test/test_channel.cc, src/lava/magma/runtime/_c_message_infrastructure/test/test_ddschannel.cc, src/lava/magma/runtime/_c_message_infrastructure/test/test_grpc_delivery.cc, src/lava/magma/runtime/_c_message_infrastructure/test/test_multiprocessing.cc, src/lava/magma/runtime/_c_message_infrastructure/test/test_shm_delivery.cc, src/lava/magma/runtime/_c_message_infrastructure/test/test_socket_delivery.cc, tests/lava/magma/runtime/message_infrastructure/test_all_delivery.py, tests/lava/magma/runtime/message_infrastructure/test_channel.py, tests/lava/magma/runtime/message_infrastructure/test_channel_block.py, tests/lava/magma/runtime/message_infrastructure/test_temp_channel.py
=> amend msg_lib cpput

src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/ros_talk_with_dds_cpp/src/publisher.cc, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/ros_talk_with_dds_py/ros_talk_with_dds_py/subscriber.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/ros_talk_with_dds_py/ros_talk_with_dds_py/utils/np_mdata_trans.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_cyclonedds_from_ros.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_cyclonedds_to_ros.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_fastdds_from_ros.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/test_fastdds_to_ros.py, src/lava/magma/runtime/_c_message_infrastructure/setenv.sh, src/lava/magma/runtime/_c_message_infrastructure/tools/log_merge.sh, src/lava/magma/runtime/message_infrastructure/__init__.py, src/lava/magma/runtime/message_infrastructure/multiprocessing.py, src/lava/magma/runtime/message_infrastructure/nx.py, src/lava/magma/runtime/message_infrastructure/ports.py, tests/lava/magma/runtime/message_infrastructure/test_all_delivery.py, tests/lava/magma/runtime/message_infrastructure/test_channel.py, tests/lava/magma/runtime/message_infrastructure/test_channel_block.py, tests/lava/magma/runtime/message_infrastructure/test_multiprocessing.py, tests/lava/magma/runtime/test_file_descriptors.py, tests/lava/tutorials/test_tutorials.py
=> Fix static analysis scan error

src/lava/magma/runtime/_c_message_infrastructure/CMakeLists.txt, src/lava/magma/runtime/message_infrastructure/__init__.py, tests/lava/magma/runtime/message_infrastructure/test_channel.py, tests/lava/magma/runtime/message_infrastructure/test_channel_block.py
=> msglib dds package install

pyproject.toml
Issue Number: #677 
Objective of pull request: Make license classifiers compatible with PyPI
=> Update pyproject.toml with PyPI compatible classifiers

pyproject.toml
Issue Number: #677 
Objective: Backport this change to enable releasing artifacts on pypi by updating to compatible license clasifiers.
=> Modify license classifiers for compatibility with pypi

prebuild.py, src/lava/magma/runtime/_c_message_infrastructure/README.md, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/cyclone_dds.cc, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/protos/fast_dds/DDSMetaData.cc, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/grpc/grpc_port.cc, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/socket/socket_port.cc, src/lava/magma/runtime/_c_message_infrastructure/examples/c_pingpong/README.md, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/README.md, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/ros_talk_with_dds_py/ros_talk_with_dds_py/subscriber.py, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/ros_talk_with_dds_py/ros_talk_with_dds_py/utils/np_mdata_trans.py, src/lava/magma/runtime/_c_message_infrastructure/tools/log_merge.sh, src/lava/magma/runtime/message_infrastructure/__init__.py, src/lava/magma/runtime/message_infrastructure/factory.py, src/lava/magma/runtime/message_infrastructure/message_infrastructure_interface.py, src/lava/magma/runtime/message_infrastructure/py_multiprocessing.py, src/lava/magma/runtime/runtime_services/runtime_service.py, tests/lava/magma/compiler/subcompilers/test_channel_builders_factory.py, tests/lava/magma/runtime/message_infrastructure/test_exception.py, tests/lava/proc/dense/test_stdp_sim.py
=> fix static analysis

src/lava/magma/runtime/_c_message_infrastructure/README.md, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/grpc/grpc_port.cc, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/socket/socket_port.cc, src/lava/magma/runtime/_c_message_infrastructure/examples/c_pingpong/README.md, src/lava/magma/runtime/_c_message_infrastructure/examples/ros2/README.md, src/lava/magma/runtime/_c_message_infrastructure/tools/log_merge.sh, src/lava/magma/runtime/message_infrastructure/__init__.py
=> fix code analysis

src/lava/magma/runtime/_c_message_infrastructure/README.md, src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/protos/fast_dds/DDSMetaData.cc, src/lava/magma/runtime/_c_message_infrastructure/examples/c_pingpong/README.md, src/lava/magma/runtime/message_infrastructure/__init__.py
=> fix cppcheck ignore

tests/lava/proc/io/test_extractor.py, tests/lava/proc/io/test_injector.py
=> Fixing tuple type hints in Injector/Extractor tests

src/lava/magma/core/process/process.py
=> Bugfix to pass the args by keyword

.github/workflows/ci.yml
Issue Number: #852 
Use macos-13 instead of latest for our CI tests. The newer MacOS version does not support python 3.9 and earlier.
-   [x] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
-   [x] Tests are part of the PR (for bug fixes / features)
-   [x] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r …
=> CI: Use macos-13 instead of latest

src/lava/proc/io/extractor.py, src/lava/proc/io/injector.py
=> Extractor and Injector async models fixed
