lava-nc/lava

- src/lava/magma/compiler/builder.py
- src/lava/magma/compiler/compiler.py
- src/lava/magma/compiler/utils.py
- src/lava/magma/core/model/interfaces.py
- src/lava/magma/core/model/py/model.py
- src/lava/magma/core/model/py/ports.py
- src/lava/magma/core/process/ports/ports.py
- src/lava/magma/runtime/runtime_service.py
- tests/lava/magma/compiler/test_compiler.py
- tests/lava/magma/core/model/test_py_model.py
- tests/lava/magma/core/process/test_lif_dense_lif.py
- tests/lava/magma/core/process/test_ports.py
- tests/lava/magma/runtime/test_get_set_var.py
- tests/lava/magma/runtime/test_ref_var_ports.py
This change allows access to variables (Vars) of another Process through the usage of RefPorts and VarPorts.
Initial enablement.
Limitations:
- Currently supports only 1:1 (RefPort to Var/VarPort) connections
> Enablement of RefPort to Var/VarPort connections

- src/lava/magma/compiler/channels/pypychannel.py
- src/lava/magma/core/model/py/model.py
- src/lava/magma/core/model/py/ports.py
- src/lava/magma/runtime/mgmt_token_enums.py
- src/lava/magma/runtime/runtime.py
- src/lava/magma/runtime/runtime_service.py
A few performance improvements:
- replace probe() plus busy waiting with select()
- use a specialized function to compare messages of enum constants
- use multiprocessing semaphore to avoid overhead of pipe
> Performance improvements

- src/lava/utils/dataloader/mnist.npy
- src/lava/utils/dataloader/mnist.py
`tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb` doesn't work if you install lava with a `pip install` as `mnist.npy` is not packaged. I fixed it by completing these to-dos.
> Fixing MNIST dataloader

- src/lava/magma/compiler/builder.py
- src/lava/magma/compiler/compiler.py
- src/lava/magma/core/model/py/model.py
- src/lava/magma/core/process/process.py
- src/lava/magma/runtime/mgmt_token_enums.py
- src/lava/magma/runtime/runtime.py
- src/lava/magma/runtime/runtime_service.py
- tests/lava/magma/runtime/test_get_set_var.py
- tests/lava/magma/runtime/test_loihi_protocol.py
- tests/lava/magma/runtime/test_runtime.py
- tests/lava/magma/runtime/test_runtime_service.py
* Reduced the number of channels between service and process
* Fixed the bug with failing monitor cases
Issue Number: Remove hacks and refactor Runtime and RuntimeService/Synchronizer #86
Objective of pull request: Reduced the number of channels between service and process
- [X ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [X ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [X ] Refactoring (no functional changes, no api changes)
- Currently we have five channels between runtime service and process model. 
- 1. Used for sending cmd from RS to PM
- 2. Used for sending ack back from PM to RS
- 3. Used for …
> Reduced the number of channels between service and process (#1)

- src/lava/proc/lif/models.py
- src/lava/proc/lif/process.py
- tests/lava/proc/lif/test_models.py
- tests/lava/proc/lif/test_process.py
- tests/lava/proc/monitor/test_monitors.py
Signed-off-by: Risbud, Sumedh <sumedh.risbud@intel.com>
Issue Number: #150 
*Objective of pull request*: To merge TernaryLIF behaviour along with related refactoring of the LIF Process
- There is no TernaryLIF
- There is a TernaryLIF, which spikes +1 or -1 depending upon which of the upper or lower thresholds was crossed.
- The development required refactoring the existing LIF Process to carve out an AbstractLIF Process. 
- Both LIF and TernaryLIF inherit from AbstractLIF
- This organization can be followed for organizing lava/proc library in general
> TernaryLIF and refactoring of LIF to inherit from AbstractLIF

- src/lava/magma/compiler/builder.py
- src/lava/magma/core/model/model.py
- src/lava/magma/core/model/py/model.py
- src/lava/magma/core/process/process.py
- src/lava/magma/core/resources.py
- src/lava/proc/dense/models.py
- src/lava/proc/io/dataloader.py
- src/lava/proc/lif/models.py
- tests/lava/magma/runtime/test_runtime_service.py
- tests/lava/proc/io/test_dataloader.py
Implemented proc_params in process model constructor and used it for dataloader processes.
Signed-off-by: bamsumit <bam_sumit@hotmail.com>
Issue Number: 
- We cannot communicate anything other than PyPorts and Vars between process and process model constructor
- Process params is available in the process model constructor.
- New resource type `HostCPU` to indicate the process model must run on Host CPU.
The execution may halt if you have overloaded the process model constructor without `proc_params` argument. The intended way to overload is
```python
def __init__(self, proc_params):
super(<YourProcModel>, self).__init__(proc_params)
```
> Proc_params for communicating arbitrary object between process and process model

- .github/workflows/ci-build.yml
Objective of pull request: Fix intermittent CI failures
- unit tests stall without error intermittently
- Use unittest module directly and allow unit tests complete either successfully or with errors, failures in a relatively short amount of time.
> Use unittest ci

- src/lava/magma/runtime/message_infrastructure/multiprocessing.py
Issue Number: #176
Objective of pull request: Fix Multiprocessing AssertionError: can only join a child process
- When unit test are run the following error is present (see: https://github.com/lava-nc/lava/runs/5132279352?check_suite_focus=true#step:5:81 for example):
packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 79, in stop
actor.join()
File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/multiprocessing/process.py", line 147, in join
assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
- actor processes can join successfully after a check, fixing "AssertionError: can only join a child process"
> Multiproc bug

- tutorials/in_depth/tutorial04_execution.ipynb
Issue Number: 
Objective of pull request: Fix tutorial 4, frame [44]
- Runtime initialization has changed and this has broken tutorial 4, frame [44].
- Update Runtime initialization for tutorial 4, frame [44] to get it working again.
> Fix tutorial04_execution.ipynb

- .github/workflows/ci-build.yml
- poetry.lock
- pyproject.toml
- tests/lava/tutorials/test_tutorials.py
- tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb
- tutorials/in_depth/tutorial05_connect_processes.ipynb
- tutorials/in_depth/tutorial07_remote_memory_access.ipynb
Issue Number: #243 
Objective of pull request: Create tests for tutorials
> Tutorial tests

- src/lava/magma/compiler/compiler_graphs.py
Signed-off-by: Risbud, Sumedh <sumedh.risbud@intel.com>
**Objective of pull request:**
Modifications to DiGraphBase class to enable recurrent topologies
- When collapsing a cycle to a single node, DiGraphBase's method did not treat single-node-self-recurrent cycles correctly.
- Changes to the collapsing code fix the issue.
> Changes in DiGraphBase class to enable recurrence

- README.md
Using `git checkout v0.4.0` leads to detached HEAD state. Update to `git switch release/v0.4.0` avoids this and correctly sets local branch to track remote branch.
> Update install instructions to switch to branch.

- src/lava/magma/compiler/compiler.py
Issue Number: 
Objective of pull request: Fixes issue of default sync domain not splitting processes according to the Node.
- [ x] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-
-
> Fix default sync domain not splitting processes according to the Node

- src/lava/magma/compiler/compiler.py
Issue Number: #288
Objective of pull request:  Add type to isinstance call _create_subcompilers to fix issue where isinstance fails by not finding type of subcompiler classes.
- [NA] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
> Add type to isinstance call

- .github/workflows/ci-build.yml
- src/lava/magma/runtime/message_infrastructure/csrc/abstract_actor.h
- src/lava/magma/runtime/message_infrastructure/csrc/abstract_channel.h
- src/lava/magma/runtime/message_infrastructure/csrc/abstract_port.h
- src/lava/magma/runtime/message_infrastructure/csrc/abstract_port_implementation.h
- src/lava/magma/runtime/message_infrastructure/csrc/multiprocessing.h
- src/lava/magma/runtime/message_infrastructure/csrc/process_model.h
- src/lava/magma/runtime/message_infrastructure/csrc/runtime.h
- src/lava/magma/runtime/message_infrastructure/csrc/shm.h
- src/lava/magma/runtime/message_infrastructure/csrc/shmem_channel.h
- src/lava/magma/runtime/message_infrastructure/csrc/shmem_port.h
- src/lava/magma/runtime/message_infrastructure/csrc/utils.h
> Fix cpplint errors for new project structure

- .gitmodules
- poetry.lock
- pyproject.toml
- src/lava/magma/runtime/message_infrastructure/CMakeLists.txt
- src/lava/magma/runtime/message_infrastructure/poetry.lock
- src/lava/magma/runtime/message_infrastructure/pyproject.toml
- src/lava/magma/runtime/message_infrastructure/setup.py
Issue Number: 
Objective of pull request: Setup sub-project for message_infrastructure 
-
-
> Setup sub project for message_infrastructure 

- src/lava/magma/core/learning/learning_rule.py
- src/lava/magma/core/model/py/connection.py
Issue Number: 
Objective of pull request: The base classes for the learning-related ProcessModels (`Connection` and its subclasses) were accessing members that are only defined in its subclasses. This PR also eliminates parts of the code duplication.
-
-
> Eliminate design issues in learning-related code

- src/lava/magma/compiler/compiler_graphs.py
- src/lava/magma/runtime/runtime_services/channel_broker/channel_broker.py
> Fixes a bug in network compilation and multiple port polling

- src/lava/magma/compiler/compiler.py
Signed-off-by: Risbud, Sumedh <sumedh.risbud@intel.com>
Objective of pull request: Fixes issue first uncovered by lava-optimization test case. CProcCompiler is called before NcProcCompiler to correctly populate ports and channels.
-
-
> Fixed the explicit ordering of subcompilers in compilation stack: C-first-Nc-second

- src/lava/magma/core/model/py/connection.py
Issue Number: #411
Objective of pull request: Fixing incorrect use of np.logical_and and np.logical_or was discovered in learning-related code in Connection ProcessModels.
- Currently, to implement `and` and `or` element-wise operations on 3 `np.ndarray` (example : `a`, `b` and `c`), the following is used :
`np.logical_and(a, b, c)`
- Replaced it with : 
`a & b & c`
> Fixing np.logical_and/or problems in Connection ProcessModels

- src/lava/utils/profiler.py
Objective of pull request: Adding a profiler base class which selects an appropriate Profiler based on the chosen RunCfg. Currently only the Loihi2HWProfiler for profiling Loihi 2 will be available, if lava-loihi is also installed (INRC members only). In the future this class can choose profiler implementations for Loihi 1, Loihi 2, CPU, GPU or other neuromorphic hardware.
- No profiler is available
- Profiler base class available to select appropriate profiler implementation
> Add Profiler base class 

- src/lava/proc/rf/process.py
Issue Number: 472
Objective of pull request: Fix improper cast in rf neuron process
- [] Tests are part of the PR (for bug fixes / features)
- Non singular rf neuron instantiations do not work
- Rf neurons with variable periods now work
The [lava-dl rf netx PR](https://github.com/lava-nc/lava-dl/pull/110) relies upon this PR being accepted.
>  Fix improper cast in rf neuron process

- src/lava/magma/core/model/py/model.py
- tests/lava/magma/runtime/test_ref_var_ports.py
> Add var port polling in host phase to flush out any pending reads

- src/lava/utils/weightutils.py
- tests/lava/utils/test_weightutils.py
Issue Number: #501 
Objective of pull request: The automatic determination of the weight exponent given the weights does fail, if all weights are 0. As this is used in the general Dense process for Loihi2HwCfg (running on Loihi 2), initializing weights with just 0 is currently not possible.
-
-
> Initialization of Dense with all-zero weights

- tests/lava/magma/runtime/test_loihi_with_async_protocol.py
> Lp with ap

- src/lava/magma/compiler/builders/runtimeservice_builder.py
> Add compile config to rs_builder

- src/lava/magma/core/model/py/model.py
- src/lava/magma/runtime/runtime_services/runtime_service.py
- tests/lava/magma/runtime/test_async_protocol.py
> Fixed Pause for Async Process

- src/lava/magma/compiler/channel_map.py
> Fixed mappin gof payload to multiple port pairs

- src/lava/magma/runtime/runtime_services/runtime_service.py
Issue Number: #659
Objective of pull request: Changing order of checks when advancing phase in LoihiPyRuntimeService.
- When we have 2 Processes with **PyLoihiProcessModels**, with : 
- Process1 requesting to go from `SPK` to `LRN`
- Process2 requesting to go from `SPK` to `POST_MGMT`
- **RuntimeService** will orchestrate the following phase transitions _within the same time step_ : 
- `SPK` -> `POST_MGMT` -> `LRN` -> `POST_MGMT` 
- **RuntimeService** will orchestrate the following phase transitions _within the same time step_ : 
- `SPK` -> `LRN` -> `POST_MGMT`
> Changing order of checks when advancing phase in LoihiPyRuntimeService

- src/lava/magma/compiler/channels/pypychannel.py
- src/lava/magma/core/model/py/model.py
- src/lava/magma/core/model/py/ports.py
Added a check to prevent re-appending the same PyPort or VarPort that is already in a process model's py_ports or var_ports list.
Adjusted CspRecvPort implementation to allocate numpy _result array once at initialization rather than on every update.
Adjusted PyRefPortVectorDense to allocate header numpy arrays the first time they are used, rather than every time a value is sent.
Issue Number: #586 
Fix incorrect append of py_ports and var_ports on each process model update, resulting in significant slowdown over time when using varports (e.g. Monitor).
- [Y] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [N] Tests are part of the PR (for bug fixes / features)
- …
> Fixed automatic append of py_ports and var_ports

- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/cyclone_dds.cc
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/cyclone_dds.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/dds.cc
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/dds.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/dds_channel.cc
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/dds_channel.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/dds_port.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/fast_dds.cc
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/dds/fast_dds.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel_proxy.cc
- src/lava/magma/runtime/_c_message_infrastructure/csrc/channel_proxy.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/core/channel_factory.cc
- src/lava/magma/runtime/_c_message_infrastructure/csrc/core/channel_factory.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/core/utils.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/message_infrastructure_py_wrapper.cc
- src/lava/magma/runtime/_c_message_infrastructure/test/test_cyclonedds_from_ros.cc
- src/lava/magma/runtime/_c_message_infrastructure/test/test_cyclonedds_to_ros.cc
- src/lava/magma/runtime/_c_message_infrastructure/test/test_ddschannel.cc
- src/lava/magma/runtime/_c_message_infrastructure/test/test_fastdds_from_ros.cc
- src/lava/magma/runtime/_c_message_infrastructure/test/test_fastdds_to_ros.cc
- tests/lava/magma/runtime/message_infrastructure/test_all_delivery.py
- tests/lava/magma/runtime/message_infrastructure/test_channel.py
> Add probe for dds

- src/lava/magma/core/process/ports/ports.py
- tests/lava/magma/core/process/ports/test_ports.py
Issue Number: #676 
- An assertion was raised when it was requested to create two different implicit var ports with the same name on the same process
- The different var ports will be created without assertion, with a numerical suffix added to the name
> Bugfix to enable monitoring aliased vars

- src/lava/magma/core/process/process.py
- tests/lava/magma/core/process/test_process.py
Issue Number: #673 
Add a method to process to create and initialize a runtime without running it.
- [Y] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [Y] Tests are part of the PR (for bug fixes / features)
- [Y] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [Y] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [Y] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [Y] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [Y] Build tests (`pytest`) …
> Added process.create_runtime method

- src/lava/utils/weightutils.py
Issue Number: 
When initializing Sparse with small but mixed weights, the truncating weights function of the weightutils round them to zero. As those weights are kept in the data field of the sparse matrix, the shape is wrong. This PR fixes this issue by removing these explicit zeros from the sparse matrix.
-
-
> Truncating weights to 0 for Sparse lead to wrong shape fixed

- src/lava/proc/dense/process.py
- src/lava/proc/sparse/process.py
Objective of pull request: The maximum delay needs to be part of the keyword arguments of the Dense process in order to use this value for the NcProcModel to determine the needed number of bits when configuring delays on Loihi 2.
This change does not affect anything else.
-
-
> Minor refactoring for DelayDense/Sparse process

- src/lava/proc/sparse/models.py
Objective of pull request: Sparse process should be able to handle all 0 delays.
-
-
> Minor change to sparse to handle all 0 delays

- .github/workflows/ci.yml
- .github/workflows/codacy_coverage_reporter.yml
Issue Number: 
Objective of pull request: With this PR, coverage reports are generated on every push and sent to Codacy for analysis.
-
-
> Coverage reports for Codacy

- src/lava/magma/runtime/_c_message_infrastructure/csrc/core/utils.h
- src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.h
- src/lava/magma/runtime/message_infrastructure/__init__.py
- src/lava/magma/runtime/message_infrastructure/ports.py
> Enhance performacne of cpp msg lib

- src/lava/magma/compiler/compiler.py
- src/lava/magma/compiler/executable.py
- src/lava/utils/profiler.py
- tests/lava/magma/runtime/test_runtime.py
Issue Number: N/A
Objective of pull request: Executable explicitly contains a flat list of *all* Processes after ProcGroups are created (all SubProcesses are resolved). This helps in propagating the Runtime to all Processes.
-   [x] Lint …
> Executable explicitly contains a flat list of *all* Processes after ProcGroups are created

- src/lava/magma/runtime/message_infrastructure/pypychannel.py
- src/lava/proc/dense/models.py
> fix static code analysis

- tests/lava/magma/core/process/test_process.py
Issue Number: #717 
Objective of pull request: Fixing create_runtime unit test.
-   [X] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
-   [X] Tests are part of the PR (for bug fixes / features)
-   [X] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [X] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
-   [X] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
-   [X] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-   [X] Build tests (`pytest`) passes locally
-   [X] Bugfix
- The …
> Fixing create_runtime unit test.

- src/lava/utils/system.py
Issue Number: #738 
Objective of pull request: Re-add lava.utils.system to fix errors in libs and lava-loihi. Mark as deprecated.
-   [X] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
-   [X] Tests are part of the PR (for bug fixes / features)
-   [X] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [X] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
-   [X] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
-   [X] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-   [X] Build …
> Re-adding deprecated lava.utils.system.

- src/lava/utils/slurm.py
- src/lava/utils/system.py
Issue Number: #739 
Objective of pull request: Fixing a bug from earlier merge due to invalid partition rows in sinfo.
-   [X] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
-   [X] Tests are part of the PR (for bug fixes / features)
-   [X] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [X] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
-   [X] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
-   [X] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-   [X] Build tests …
> Fix partition parse bug for internal vLab

- src/lava/proc/conv/models.py
Issue Number: #750
Objective of pull request: Fix recurrent python conv processes creates a deadlock
-   [x] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed …
> Fix conv python model to send() before recv()

- src/lava/proc/sparse/process.py
- tests/lava/proc/sparse/test_process.py
Objective of pull request: Allow np.array as input weights for Sparse
-   [x] Tests are part of the PR (for bug fixes / features)
-   [x] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-   [x] Build tests (`pytest`) passes locally
- …
> Allow np.array as input weights for Sparse

- src/lava/magma/compiler/builders/channel_builder.py
> Add sender and receiver information in watchdog logs

- src/lava/magma/compiler/builders/channel_builder.py
- src/lava/magma/core/process/variable.py
- src/lava/proc/bit_check/models.py
- src/lava/proc/bit_check/process.py
- tests/lava/proc/bit_check/test_models.py
- tests/lava/proc/bit_check/test_process.py
- tutorials/in_depth/tutorial10_sigma_delta_neurons.ipynb
Issue Number: #801
Objective of pull request: Add a BitCheck process. This short and simple ProcessModel can be used for quick checking of bit-accurate process runs as to whether bits will overflow when running on hardware.
-   [X] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
-   [X] Tests are part of the PR (for bug fixes / features)
-   [X] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
-   [X] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
-   [X] Lint …
> Add BitCheck Process

- src/lava/proc/s4d/models.py
- src/lava/proc/s4d/process.py
- src/lava/proc/sdn/process.py
- tests/lava/proc/s4d/s4d_A.dat.npy
- tests/lava/proc/s4d/s4d_B.dat.npy
- tests/lava/proc/s4d/s4d_C.dat.npy
- tests/lava/proc/s4d/test_models.py
- tests/lava/proc/s4d/test_process.py
- tests/lava/proc/s4d/utils.py
Objective of pull request: Add S4D neurons.
-   [x] Tests are part of the PR (for bug fixes / features)
-   [x] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-   [x] Build tests (`pytest`) passes locally
-   [ ] Bugfix
-   [x] …
> SigmaS4Delta Neuronmodel and Layer with Unittests

- src/lava/proc/spiker/process.py
Adds a spiker with 32bit messages
Also, this spiker actually has a correct definition of period. It sends its first spike after 'period' number of time steps.
> Spiker with 32bit

- src/lava/magma/core/process/ports/ports.py
- src/lava/magma/runtime/runtime.py
- src/lava/proc/io/extractor.py
- src/lava/proc/io/injector.py
- tests/lava/magma/runtime/test_external_pipe_io.py
- tests/lava/proc/io/test_extractor.py
- tests/lava/proc/io/test_injector.py
Issue Number: 
Objective of pull request: Give an alternative (better) implementation of Injector and Extractor main functionality without wrapping it into a Lava Process.
-   [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r …
> Alternative to Injector/Extractor Processes

- src/lava/magma/compiler/compiler.py
- src/lava/magma/compiler/subcompilers/py/pyproc_compiler.py
- tests/lava/magma/compiler/test_compiler.py
Objective of pull request: It should be possible to give a set partitioning to the compiler to bypass the iterative finding of a partitioning.
-   [x] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- …
> Enable manual partitioning
